package com.newtube.mobile.player;

import android.content.Context;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Build.VERSION;
import android.util.TypedValue;
import android.view.View;
import android.view.accessibility.CaptioningManager;
import android.view.accessibility.CaptioningManager.CaptionStyle;

import androidx.annotation.RequiresApi;
import androidx.core.content.ContextCompat;
import androidx.media3.common.Player;
import androidx.media3.common.text.Cue;
import androidx.media3.common.text.CueGroup;
import androidx.media3.ui.CaptionStyleCompat;
import androidx.media3.ui.SubtitleView;

import com.liskovsoft.sharedutils.helpers.Helpers;
import com.liskovsoft.smartyoutubetv2.common.R;
import com.liskovsoft.smartyoutubetv2.common.exoplayer.other.SubtitleStyle;
import com.liskovsoft.smartyoutubetv2.common.prefs.PlayerData;
import com.liskovsoft.smartyoutubetv2.common.prefs.common.DataChangeBase.OnDataChange;

import java.util.ArrayList;
import java.util.List;

/**
 * Media3 twin of the shared {@code SubtitleManager}: applies the user's stored
 * {@link SubtitleStyle} to a media3 {@link SubtitleView} and feeds it cues as a
 * {@link Player.Listener} (media3 dropped the separate TextOutput registration). The
 * repeated-lines cleanup for autogenerated subs is carried over unchanged.
 */
public class Media3SubtitleManager implements Player.Listener, OnDataChange {
    private final SubtitleView mSubtitleView;
    private final Context mContext;
    private final PlayerData mPlayerData;
    private CharSequence mSubsBuffer;

    public Media3SubtitleManager(SubtitleView subtitleView) {
        mContext = subtitleView.getContext();
        mSubtitleView = subtitleView;
        mPlayerData = PlayerData.instance(mContext);
        mPlayerData.setOnChange(this);
        configureSubtitleView();
    }

    @Override
    public void onDataChange() {
        configureSubtitleView();
    }

    @Override
    public void onCues(CueGroup cueGroup) {
        if (mSubtitleView != null) {
            mSubtitleView.setCues(forceCenterAlignment(cueGroup.cues));
        }
    }

    public void show(boolean show) {
        if (mSubtitleView != null) {
            mSubtitleView.setVisibility(show ? View.VISIBLE : View.GONE);
        }
    }

    /** Same autogenerated-subs dedup as the legacy manager, on media3's immutable Cue. */
    private List<Cue> forceCenterAlignment(List<Cue> cues) {
        List<Cue> result = new ArrayList<>();

        for (Cue cue : cues) {
            if (cue.text == null) {
                result.add(cue);
                continue;
            }

            final String textStr = cue.text.toString();
            if (Helpers.endsWithAny(textStr, "\n", " ")) { // vtt subs format
                mSubsBuffer = textStr;
            } else if (textStr.contains("\n")) { // ttml subs format
                CharSequence text;

                if (mSubsBuffer != null && textStr.contains(mSubsBuffer)) {
                    text = textStr.replace(mSubsBuffer, "").replace("\n", "");
                } else {
                    text = textStr;
                }

                result.add(new Cue.Builder().setText(text).build()); // sub centered by default

                String[] split = textStr.split("\n");
                mSubsBuffer = split.length == 2 ? split[1] : textStr;
            } else {
                CharSequence text = mSubsBuffer != null ? textStr.replace(mSubsBuffer, "") : textStr;
                result.add(new Cue.Builder().setText(text).build()); // sub centered by default
                mSubsBuffer = text;
            }
        }

        return result;
    }

    private void configureSubtitleView() {
        if (mSubtitleView != null) {
            // disable default style
            mSubtitleView.setApplyEmbeddedStyles(false);

            SubtitleStyle subtitleStyle = mPlayerData.getSubtitleStyle();

            if (subtitleStyle.isSystem()) {
                if (VERSION.SDK_INT >= 19) {
                    applySystemStyle();
                }
            } else {
                applyStyle(subtitleStyle);
            }

            mSubtitleView.setBottomPaddingFraction(mPlayerData.getSubtitlePosition());
        }
    }

    private void applyStyle(SubtitleStyle subtitleStyle) {
        int textColor = ContextCompat.getColor(mContext, subtitleStyle.subsColorResId);
        int outlineColor = ContextCompat.getColor(mContext, R.color.black);
        int backgroundColor = ContextCompat.getColor(mContext, subtitleStyle.backgroundColorResId);

        CaptionStyleCompat style =
                new CaptionStyleCompat(textColor,
                        backgroundColor, Color.TRANSPARENT,
                        subtitleStyle.captionStyle,
                        outlineColor, Typeface.DEFAULT_BOLD);
        mSubtitleView.setStyle(style);

        mSubtitleView.setFixedTextSize(TypedValue.COMPLEX_UNIT_PX, getTextSizePx());
    }

    @RequiresApi(19)
    private void applySystemStyle() {
        CaptioningManager captioningManager =
                (CaptioningManager) mContext.getSystemService(Context.CAPTIONING_SERVICE);

        if (captioningManager != null) {
            CaptionStyle userStyle = captioningManager.getUserStyle();

            CaptionStyleCompat style =
                    new CaptionStyleCompat(userStyle.foregroundColor,
                            userStyle.backgroundColor, VERSION.SDK_INT >= 21 ? userStyle.windowColor : Color.TRANSPARENT,
                            userStyle.edgeType,
                            userStyle.edgeColor, userStyle.getTypeface());
            mSubtitleView.setStyle(style);

            mSubtitleView.setFixedTextSize(TypedValue.COMPLEX_UNIT_PX, getTextSizePx() * captioningManager.getFontScale());
        }
    }

    private float getTextSizePx() {
        float textSizePx = mSubtitleView.getContext().getResources().getDimension(R.dimen.subtitle_text_size);
        return textSizePx * mPlayerData.getSubtitleScale();
    }
}
